
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    working_dir: /app
    container_name: portfolio-container
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
    ports:
      - "${APP_DEV_PORT:-5173}:5173"
      - "${APP_PROD_PORT:-8080}:80"